services:
  database:
    build: ./database
    ports:
      - "8001:8000"
    volumes:
      - ./database/3d_models:/app/3d_models
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SIMULATION_URL=http://simulation:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  simulation:
    build: ./simulation
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=http://database:8000
    depends_on:
      - database
    volumes:
      - ./database/3d_models:/3d_models

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=http://database:8000
      - SIMULATION_URL=http://simulation:8000
    depends_on:
      - database
      - simulation